# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-08 22:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20171008_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='imagen',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='events'),
            preserve_default=False,
        ),
    ]
