# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-08 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_evento_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='imagen',
            field=models.ImageField(upload_to='events/static/media'),
        ),
    ]
